### ISSUE TITLE
ofxGtk compile error

### ISSUE THREAD

**Issue by d3cod3** [underdoeg/ofxGtk#1]
Hi, i'm trying to compile the ofxGtk example and i'm having troubles with two files:

ofxGtkWidget.h (1) and ofxGtkWindow.h (2)

the error is on build:

file 1, line 14: class ofxGtkWidget: public Gtk::Widget, public ofAppBaseGLWindow {

and 

file 2, line 7: class ofxGtkBaseWindow: public Gtk::ApplicationWindow, public ofAppBaseGLWindow {

(same issue)

with error: expected class-name before '{' token

can't find why, do you have some ideas?

thank you in advance and thank you so much for your great work!

**Comment by d3cod3** [comment]
Ups, i forget some system info:

Ubuntu 14.04, Codeblocks 13.12, OF 0.8.4

thanks again

**Comment by underdoeg** [comment]
Hin.sorry I totally overlooked your issue. I have since rewritten the addon. So I will close this. Sorry again...
